# fUNCTION IN PYTHON

# syntax
# --------------------
# def name(argumnets):
	
	
# 	body of the function
	

# # ad	d()
# def add(argumnets):
# 	print(' i am the first funting function')
# print(add)
# add(parametrs/values)---------------------> function call




# argumnets:
# ======================


# 1.postional argumnets
# 2.defua;t argumnets
# 3.keyword argumnets
# 4.arbitary or varable length argumnets

# 1.postional argumnets
# -------------------------------

# def add(a,b,c):
# 	print(a+b)
# add(45,3,45)

# 2.defualt argumnets
# -------------------------


# def add(a=56,b=5):
# 	print(a+b)
# add()


# 3.keyword argumnets
# -------------------------
# def add(a,b):
# 	print(a+b)

# add(a=4,b =6)









